language: r
cache: packages

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - beast-dev/RBeast
  - richelbilderbeek/ribir

before_script:
  - sudo apt-get install -qq oracle-java8-installer # Java 8
  - sudo apt-get install oracle-java8-set-default
  - ./install_beast2.sh

script: 
  - |
    R CMD build .
    travis_wait 30 R CMD check beautier*tar.gz

after_success:
  - Rscript -e 'lintr::lint_package()'
  - travis_wait 30 Rscript -e 'covr::codecov()'
  - travis_wait 30 Rscript -e 'goodpractice::gp()'

after_failure:
  # - sudo Rscript install_this_r_package.R
  # - Rscript -e 'library(beautier); testit::assert(has_beast2())'
  - cat /home/travis/build/richelbilderbeek/beautier/..Rcheck/00install.out
  - cat /home/travis/build/richelbilderbeek/beautier/..Rcheck/00check.log
  - cd ~; find . | egrep "beast"
  - cd ~; find . | egrep "\.log"
  - cd ~; find . | egrep "\.trees"
  - cd ~; find . | egrep "\.xml"
  - cd ~; find . | egrep "\.xml\.state"
  - cd ~; find . | egrep "\.fasta"
  - cat /home/travis/build/richelbilderbeek/beautier/..Rcheck/tests/testthat/testthat.log
